name: Deploy nginx to the development stand
on: workflow_dispatch
permissions: {}
jobs:
  deploy_nginx:
    name: Deploy nginx
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Copy files via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "html/*"
          target: "~/front/html"
          strip_components: 1
      - name: Copy files via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "nginx/*"
          target: "~/nginx"
          strip_components: 1
      - name: Execute Docker Run via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker stop nginx || true
            docker rm nginx || true
            docker run -d \
              --name nginx \
              -p 80:80 \
              -v /home/github/front/html/:/usr/share/nginx/html/ \
              -v /home/github/nginx/nginx/conf-files/:/etc/nginx/conf.d/ \
              -v /home/github/nginx/nginx.conf:/etc/nginx/nginx.conf \
              nginx
